apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4wj0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-4wj0@sha256:4bc03713381366fabb669a658ca9d70acbabdfd7065f70b9958c450ec721f947
        name: my-nodejs
        resources: {}
status: {}
